// <auto-generated />
using BlazorCheckboxes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCheckboxes.Migrations;

[DbContext(typeof(CounterContext))]
[Migration("20240701201807_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

        modelBuilder.Entity("BlazorCheckboxes.Counter", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Value")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("Counters");
            });
#pragma warning restore 612, 618
    }
}
